### ISSUE TITLE
Add /system/vm in the tree

### ISSUE THREAD

**Issue by samary** [quattor/template-library-core#124]
In order to manage the VM part in the profile, I would like to add a new type 'vm' under /system/ (/system/vm) so we can hook every virtualization technology underneath (/system/vm/opennebula & /system/vm/openstack).
This is meant to avoid having every existing virtualization technology under /system itself

**Comment by samary** [comment]
What do you think about that change (backward incompatible with related components) @guillaume-philippon @alvarosimon

**Comment by guillaume-philippon** [comment]
We don't use /system/openstack at LAL and I think just ncm-opennebula component should use it if it is.

**Comment by alvarosimon** [comment]
@samary @guillaume-philippon  At this moment for ncm-opennebula component we are using `/software/components/opennebula/..` tree this is included in the code:
`my $base = "/software/components/opennebula";`

But I think, if I'm not mistaken that @samary is referring to the aii to manage the VMs running in a cloud framework, isn't it? and yes we don't use `/system/vm/..` we are using directly `/system/hardware` to convert a real machine into a VM appliance, this use case is quite useful for us. I think that @samary is asking for another use case (correct me if I'm wrong), that means do not convert a real machine into a VM, instead of that provide directly the VM requirements within quattor tree and start and manage the VM in your cloud framework. I think that this is also a valid user case and we can support both and yes `/system/vm` looks a good place, but please correct me if I misunderstood your request.

**Comment by samary** [comment]
As there are no plan to use other virtualization system that can fill this /system branch, we can keep it as it is.
I'm closing this issue (feel free to reopen it if you think there should be a more abstract system).
