### ISSUE TITLE
update partition flags

### ISSUE THREAD

**Issue by stdweird** [quattor/template-library-core#152]
see https://www.gnu.org/software/parted/manual/html_node/set.html for list, need in particular `esp` flag for generic (non-gpt) uefi support

one can use the `boot` flag on  gpt for now.

See also https://github.com/quattor/ncm-lib-blockdevices/issues/81

**Comment by jouvin** [comment]
BTW, the template librarary (`standard/filesystem/config`)  currently sets `bios_grub` flag instead of boot. Do you suggest changing for `boot`? Or setting both? This is a bit strange: according to `parted` doc you mentioned, `boot` is supposed to be used with label types other than GPT when `bios_grub` is for GPT only. But your experience suggests that `boot` is ok also with GPT and I agree that this is more pervasive.

**Comment by stdweird** [comment]
`bios_grub` is for legacy bios partiton only (aka biosboot), maybe it doesn't harm, but i don't see the point. (from anaconda output, i've seen anaconda stip all flags before seting boot; so make sure this is tested)
the esp flag explanation is pretty clear: on gpt, it's the same flag as boot. setting esp is better as that is what is documented. setting boot on gpt is a temporary hack
