### ISSUE TITLE
volgroup_required option

### ISSUE THREAD

**Issue by seraf1** [quattor/template-library-core#61]
In Quattor 14.2.1 The Quattor file / aii / ks / config.pan ends with the line:
```pan
"/system/aii/osinstall/ks/volgroup_required" ?= true;
```

But from with Quattor 14.6, this line has turned into:
```pan
"/system/aii/osinstall/ks/volgroup_required" = true;
```

This option is no longer overloaded by SL6 variant, so that the volgroup always appears in the ks file and therefore causes an error.

**Comment by jouvin** [comment]
@seraf1 for me this is correct. This option is there only to say that when you are initializing LVM logical volumes in the KS file, you should add the necessary LVM volume group initialization too. This is always required since SL4... and I have never seen a problem with this either in EL6 or EL7. It would be good if you could provide an example where it causes problem.

BTW, I suggest to close this issue and reopen it in AII repo, as this file is imported from AII and not maintain directly in this repo... (this repo contains several parts imported from other repos during the release process, in particular AII related templates (`quattor/aii`) and templates for configuring componetns (`components`).

**Comment by seraf1** [comment]
Hello,
In version 14.6, the option is always active (= in place of? = In the template), and this option is always enabled in the file ks which causes an error in the installation.
I will provide examples next week.

**Comment by jouvin** [comment]
As I said, for me this is strange because we install machines very frequently and have not seen any errors. Anyway 14.6 i really old and obsolete, it would be good if you could test with something reasonably recent, 15.2 ideally, at least 14.10. After your tests, if the problem persists, please, reopen the issue in the AII repo (referring to this one).
I close this one as the code involved is not maintained directly in this repo.
